"""Streamlit UI for preparing Water Cooler CEO report email drafts."""

from __future__ import annotations

import pandas as pd
import streamlit as st

from config import BRAND_COLORS, DEFAULT_PERIOD, MAX_RECIPIENTS
from email_sender import (
    build_match_table,
    extract_reports_from_zip,
    format_attachment_filename,
    generate_eml_zip,
    log_to_csv,
    read_recipients_csv,
    render_subject,
    render_text_body,
    validate_recipients,
)


st.set_page_config(
    page_title="Water Cooler CEO Email Tool",
    page_icon="WC",
    layout="wide",
)


def css() -> str:
    return f"""
    <style>
    :root {{
      --wc-navy: {BRAND_COLORS["navy"]};
      --wc-teal: {BRAND_COLORS["teal"]};
      --wc-aqua: {BRAND_COLORS["aqua"]};
      --wc-gold: {BRAND_COLORS["gold"]};
      --wc-coral: {BRAND_COLORS["coral"]};
      --wc-paper: {BRAND_COLORS["paper"]};
      --wc-line: {BRAND_COLORS["line"]};
    }}
    .block-container {{ padding-top: 1.5rem; padding-bottom: 2.2rem; }}
    h1, h2, h3 {{ color: var(--wc-navy); }}
    .wc-header {{
      background: linear-gradient(90deg, var(--wc-navy), #18577D);
      color: white;
      border-radius: 8px;
      padding: 1.2rem 1.4rem;
      margin-bottom: 1rem;
    }}
    .wc-header h1 {{ color: white; margin: 0; font-size: 2rem; }}
    .wc-header p {{ color: var(--wc-aqua); margin: 0.35rem 0 0; }}
    [data-testid="stMetric"] {{
      background: var(--wc-paper);
      border: 1px solid var(--wc-line);
      border-radius: 8px;
      padding: 0.8rem 0.9rem;
    }}
    </style>
    """


def empty_manual_rows() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"first_name": "", "last_name": "", "email": "", "org_name": ""}
            for _ in range(5)
        ]
    )


def styled_status(df: pd.DataFrame):
    def row_style(row):
        color = BRAND_COLORS["teal"] if row["Status"] == "Ready" else BRAND_COLORS["coral"]
        return [
            f"background-color: {color}; color: white; font-weight: 700;"
            if column == "Status"
            else ""
            for column in row.index
        ]

    return df.style.apply(row_style, axis=1)


st.markdown(css(), unsafe_allow_html=True)
st.markdown(
    """
    <div class="wc-header">
      <h1>Water Cooler CEO Email Tool</h1>
      <p>Match engagement reports, review each email, and download ready-to-send draft files.</p>
    </div>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.header("Batch settings")
    period = st.text_input("Reporting period", value=DEFAULT_PERIOD)
    st.caption("This appears in the email subject and body.")

report_zip = st.file_uploader("Upload report ZIP from the keycard reporting app", type=["zip"])

if not report_zip:
    st.info("Start by uploading the report ZIP generated by the keycard reporting app.")
    st.stop()

try:
    reports = extract_reports_from_zip(report_zip.getvalue())
except Exception as exc:
    st.error(f"Could not read report ZIP: {exc}")
    st.stop()

if not reports:
    st.error("No organization PDF reports were found in the ZIP.")
    st.stop()

report_cols = st.columns(3)
report_cols[0].metric("PDF reports found", len(reports))
report_cols[1].metric("Max recipients", MAX_RECIPIENTS)
report_cols[2].metric("Output", "Email draft ZIP")

st.subheader("Recipients")
input_mode = st.radio("Recipient input method", ["Upload CSV", "Manual entry"], horizontal=True)

recipients = pd.DataFrame()
recipient_errors: list[str] = []

if input_mode == "Upload CSV":
    recipient_csv = st.file_uploader("Upload recipient CSV", type=["csv"])
    st.caption("Required columns: first_name, last_name, email, org_name")
    if recipient_csv:
        try:
            recipients, recipient_errors = read_recipients_csv(recipient_csv)
        except Exception as exc:
            recipient_errors = [f"Could not read recipient CSV: {exc}"]
else:
    manual_df = st.data_editor(
        st.session_state.get("manual_recipients", empty_manual_rows()),
        num_rows="dynamic",
        use_container_width=True,
        hide_index=True,
        column_config={
            "first_name": st.column_config.TextColumn("First name", required=True),
            "last_name": st.column_config.TextColumn("Last name"),
            "email": st.column_config.TextColumn("Email", required=True),
            "org_name": st.column_config.TextColumn("Organization", required=True, width="large"),
        },
    )
    st.session_state["manual_recipients"] = manual_df
    recipients, recipient_errors = validate_recipients(manual_df)

if recipient_errors:
    for error in recipient_errors:
        st.warning(error)

if recipients.empty:
    st.stop()

match_table = build_match_table(recipients, reports)
match_table["subject"] = match_table.apply(
    lambda row: render_subject(row["first_name"], row["org_name"], period), axis=1
)
match_table["body"] = match_table.apply(
    lambda row: render_text_body(row["first_name"], row["org_name"], period), axis=1
)

preview = match_table.rename(
    columns={
        "recipient_name": "Recipient Name",
        "email": "Email",
        "org_name": "Org",
        "matched_report": "Matched Report",
        "match_score": "Match Score",
        "status": "Status",
    }
)[["Recipient Name", "Email", "Org", "Matched Report", "Match Score", "Status"]]

st.subheader("Report matching preview")
st.dataframe(styled_status(preview), use_container_width=True, hide_index=True, height=300)

ready_count = int((match_table["status"] == "Ready").sum())
blocked_count = len(match_table) - ready_count
status_cols = st.columns(3)
status_cols[0].metric("Recipients loaded", len(match_table))
status_cols[1].metric("Ready drafts", ready_count)
status_cols[2].metric("Blocked", blocked_count)

if blocked_count:
    st.error("Some recipients do not have a matched report. Fix the org name before building drafts.")

st.subheader("Email draft review")
st.caption("Review the full draft, edit the subject/body, and open the exact PDF that will be attached.")

report_lookup = {report.filename: report for report in reports}
edited_rows = []

for idx, row in match_table.iterrows():
    ready = row["status"] == "Ready"
    cc = row.get("cc", "")
    bcc = row.get("bcc", "")
    with st.container(border=True):
        title_cols = st.columns([0.8, 2.1, 2.4, 2.7])
        include = title_cols[0].checkbox(
            "Include",
            value=bool(row["include"]) and ready,
            disabled=not ready,
            key=f"include_{idx}_{row['email']}",
        )
        title_cols[1].markdown(f"**Recipient**  \n{row['recipient_name']}")
        title_cols[2].markdown(f"**Organization**  \n{row['org_name']}")
        title_cols[3].markdown(f"**Email**  \n{row['email']}")

        if ready:
            report = report_lookup.get(row["matched_report"])
            if report:
                st.download_button(
                    f"📎 Download attached PDF: {format_attachment_filename(row['org_name'], period)}",
                    data=report.content,
                    file_name=format_attachment_filename(row["org_name"], period),
                    mime="application/pdf",
                    key=f"pdf_download_{idx}_{row['email']}",
                )
        else:
            st.warning("No matched PDF yet. Fix this recipient's organization name before building drafts.")

        subject = st.text_input(
            "Subject",
            value=row["subject"],
            key=f"subject_{idx}_{row['email']}",
            disabled=not ready,
        )
        cc_col, bcc_col = st.columns(2)
        cc = cc_col.text_input(
            "CC (optional, comma-separated)",
            value=row.get("cc", ""),
            key=f"cc_{idx}_{row['email']}",
        )
        bcc = bcc_col.text_input(
            "BCC (optional, comma-separated)",
            value=row.get("bcc", ""),
            key=f"bcc_{idx}_{row['email']}",
        )
        body = st.text_area(
            "Email body",
            value=row["body"],
            height=320,
            key=f"body_{idx}_{row['email']}",
            disabled=not ready,
        )

    edited_rows.append(
        {
            "include": bool(include) and ready,
            "first_name": row["first_name"],
            "last_name": row["last_name"],
            "recipient_name": row["recipient_name"],
            "email": row["email"],
            "org_name": row["org_name"],
            "matched_report": row["matched_report"],
            "match_score": row["match_score"],
            "status": row["status"],
            "subject": subject,
            "body": body,
            "cc": cc,
            "bcc": bcc,
        }
    )

edited = pd.DataFrame(edited_rows)
edited.loc[edited["status"] != "Ready", "include"] = False

selected_ready = edited[(edited["include"] == True) & (edited["status"] == "Ready")]
st.caption(f"{len(selected_ready)} ready draft(s) selected.")

confirm = st.checkbox("I reviewed every selected email and attachment.")
build_disabled = selected_ready.empty or not confirm
if st.button("Build reviewed email draft ZIP", use_container_width=True, disabled=build_disabled):
    with st.spinner("Building email draft files..."):
        eml_zip, log_df = generate_eml_zip(edited, reports, period)
    st.session_state["eml_zip"] = eml_zip
    st.session_state["draft_log"] = log_df
    st.success("Draft email files are ready to download.")

if "eml_zip" in st.session_state:
    st.download_button(
        "Download reviewed email draft ZIP",
        data=st.session_state["eml_zip"],
        file_name="water_cooler_outlook_drafts.zip",
        mime="application/zip",
        use_container_width=True,
    )

if "draft_log" in st.session_state:
    st.subheader("Draft log")
    log_df = st.session_state["draft_log"]
    st.dataframe(log_df, use_container_width=True, hide_index=True)
    st.download_button(
        "Download draft log CSV",
        data=log_to_csv(log_df),
        file_name="water_cooler_draft_log.csv",
        mime="text/csv",
        use_container_width=True,
    )
