"""Streamlit UI for sending Water Cooler CEO report emails."""

from __future__ import annotations

from io import BytesIO

import pandas as pd
import streamlit as st

from config import BRAND_COLORS, DEFAULT_PERIOD, MAX_RECIPIENTS, SENDER_FALLBACK_EMAIL, SENDER_FALLBACK_NAME
from email_sender import (
    build_match_table,
    extract_reports_from_zip,
    generate_eml_zip,
    get_smtp_settings,
    log_to_csv,
    read_recipients_csv,
    render_subject,
    render_text_body,
    send_emails_via_smtp,
    validate_recipients,
)


st.set_page_config(
    page_title="Water Cooler CEO Email Tool",
    page_icon="WC",
    layout="wide",
)


def css() -> str:
    return f"""
    <style>
    :root {{
      --wc-navy: {BRAND_COLORS["navy"]};
      --wc-teal: {BRAND_COLORS["teal"]};
      --wc-aqua: {BRAND_COLORS["aqua"]};
      --wc-gold: {BRAND_COLORS["gold"]};
      --wc-coral: {BRAND_COLORS["coral"]};
      --wc-paper: {BRAND_COLORS["paper"]};
      --wc-line: {BRAND_COLORS["line"]};
    }}
    .block-container {{ padding-top: 1.5rem; padding-bottom: 2.2rem; }}
    h1, h2, h3 {{ color: var(--wc-navy); }}
    .wc-header {{
      background: linear-gradient(90deg, var(--wc-navy), #18577D);
      color: white;
      border-radius: 8px;
      padding: 1.2rem 1.4rem;
      margin-bottom: 1rem;
    }}
    .wc-header h1 {{ color: white; margin: 0; font-size: 2rem; }}
    .wc-header p {{ color: var(--wc-aqua); margin: 0.35rem 0 0; }}
    [data-testid="stMetric"] {{
      background: var(--wc-paper);
      border: 1px solid var(--wc-line);
      border-radius: 8px;
      padding: 0.8rem 0.9rem;
    }}
    </style>
    """


def empty_manual_rows() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {"first_name": "", "last_name": "", "email": "", "org_name": ""}
            for _ in range(5)
        ]
    )


def styled_status(df: pd.DataFrame):
    def row_style(row):
        color = BRAND_COLORS["teal"] if row["Status"] == "Ready" else BRAND_COLORS["coral"]
        return [
            f"background-color: {color}; color: white; font-weight: 700;"
            if column == "Status"
            else ""
            for column in row.index
        ]

    return df.style.apply(row_style, axis=1)


st.markdown(css(), unsafe_allow_html=True)
st.markdown(
    """
    <div class="wc-header">
      <h1>Water Cooler CEO Email Tool</h1>
      <p>Match engagement reports, review draft emails, and send or export .eml files.</p>
    </div>
    """,
    unsafe_allow_html=True,
)

with st.sidebar:
    st.header("Batch settings")
    period = st.text_input("Reporting period", value=DEFAULT_PERIOD)
    st.caption("This appears in the email subject and body.")
    st.divider()
    st.subheader("SMTP status")
    smtp_settings, smtp_missing = get_smtp_settings()
    if smtp_missing:
        st.warning("SMTP not ready. Use .eml mode or add the missing .env values.")
        st.caption(", ".join(smtp_missing))
    else:
        st.success(f"SMTP ready for {smtp_settings.sender_email}")

report_zip = st.file_uploader("Upload report ZIP from the keycard reporting app", type=["zip"])

if not report_zip:
    st.info("Start by uploading the report ZIP generated by the keycard reporting app.")
    st.stop()

try:
    reports = extract_reports_from_zip(report_zip.getvalue())
except Exception as exc:
    st.error(f"Could not read report ZIP: {exc}")
    st.stop()

if not reports:
    st.error("No organization PDF reports were found in the ZIP.")
    st.stop()

report_cols = st.columns(3)
report_cols[0].metric("PDF reports found", len(reports))
report_cols[1].metric("Max recipients", MAX_RECIPIENTS)
report_cols[2].metric("Sending mode", "SMTP or .eml")

st.subheader("Recipients")
input_mode = st.radio("Recipient input method", ["Upload CSV", "Manual entry"], horizontal=True)

recipients = pd.DataFrame()
recipient_errors: list[str] = []

if input_mode == "Upload CSV":
    recipient_csv = st.file_uploader("Upload recipient CSV", type=["csv"])
    st.caption("Required columns: first_name, last_name, email, org_name")
    if recipient_csv:
        try:
            recipients, recipient_errors = read_recipients_csv(recipient_csv)
        except Exception as exc:
            recipient_errors = [f"Could not read recipient CSV: {exc}"]
else:
    manual_df = st.data_editor(
        st.session_state.get("manual_recipients", empty_manual_rows()),
        num_rows="dynamic",
        use_container_width=True,
        hide_index=True,
        column_config={
            "first_name": st.column_config.TextColumn("First name", required=True),
            "last_name": st.column_config.TextColumn("Last name"),
            "email": st.column_config.TextColumn("Email", required=True),
            "org_name": st.column_config.TextColumn("Organization", required=True, width="large"),
        },
    )
    st.session_state["manual_recipients"] = manual_df
    recipients, recipient_errors = validate_recipients(manual_df)

if recipient_errors:
    for error in recipient_errors:
        st.warning(error)

if recipients.empty:
    st.stop()

match_table = build_match_table(recipients, reports)
match_table["subject"] = match_table.apply(
    lambda row: render_subject(row["first_name"], row["org_name"], period), axis=1
)
match_table["body"] = match_table.apply(
    lambda row: render_text_body(row["first_name"], row["org_name"], period), axis=1
)

preview = match_table.rename(
    columns={
        "recipient_name": "Recipient Name",
        "email": "Email",
        "org_name": "Org",
        "matched_report": "Matched Report",
        "match_score": "Match Score",
        "status": "Status",
    }
)[["Recipient Name", "Email", "Org", "Matched Report", "Match Score", "Status"]]

st.subheader("Report matching preview")
st.dataframe(styled_status(preview), use_container_width=True, hide_index=True, height=300)

ready_count = int((match_table["status"] == "Ready").sum())
blocked_count = len(match_table) - ready_count
status_cols = st.columns(3)
status_cols[0].metric("Recipients loaded", len(match_table))
status_cols[1].metric("Ready to send", ready_count)
status_cols[2].metric("Blocked", blocked_count)

if blocked_count:
    st.error("Some recipients do not have a matched report. Fix the org name before sending.")

st.subheader("Email draft review")
st.caption("Edit subject or body here before generating .eml files or sending via SMTP.")
editable_columns = [
    "send",
    "recipient_name",
    "email",
    "org_name",
    "matched_report",
    "match_score",
    "status",
    "subject",
    "body",
]
edited = st.data_editor(
    match_table[editable_columns],
    use_container_width=True,
    hide_index=True,
    height=520,
    disabled=["recipient_name", "email", "org_name", "matched_report", "match_score", "status"],
    column_config={
        "send": st.column_config.CheckboxColumn("Send", help="Only ready rows can be sent."),
        "recipient_name": st.column_config.TextColumn("Recipient", width="medium"),
        "email": st.column_config.TextColumn("Email", width="medium"),
        "org_name": st.column_config.TextColumn("Organization", width="large"),
        "matched_report": st.column_config.TextColumn("Attached PDF", width="large"),
        "match_score": st.column_config.NumberColumn("Match score", format="%.1f"),
        "status": st.column_config.TextColumn("Status"),
        "subject": st.column_config.TextColumn("Subject", width="large"),
        "body": st.column_config.TextColumn("Email body", width="large"),
    },
)

details = match_table[["first_name", "last_name"]].copy()
edited = pd.concat([details, edited], axis=1)
edited.loc[edited["status"] != "Ready", "send"] = False

selected_ready = edited[(edited["send"] == True) & (edited["status"] == "Ready")]
st.caption(f"{len(selected_ready)} ready email(s) selected.")

action_cols = st.columns(2)

with action_cols[0]:
    if st.button("Build .eml ZIP", use_container_width=True, disabled=selected_ready.empty):
        eml_zip, log_df = generate_eml_zip(
            edited,
            reports,
            period,
            sender_email=smtp_settings.sender_email if smtp_settings else SENDER_FALLBACK_EMAIL,
            sender_name=smtp_settings.sender_name if smtp_settings else SENDER_FALLBACK_NAME,
        )
        st.session_state["eml_zip"] = eml_zip
        st.session_state["send_log"] = log_df

    if "eml_zip" in st.session_state:
        st.download_button(
            "Download .eml ZIP",
            data=st.session_state["eml_zip"],
            file_name="water_cooler_email_drafts.zip",
            mime="application/zip",
            use_container_width=True,
        )

with action_cols[1]:
    confirm = st.checkbox("I reviewed every selected email and attachment.")
    send_disabled = selected_ready.empty or bool(smtp_missing) or not confirm
    if st.button("Send selected via SMTP", use_container_width=True, disabled=send_disabled):
        with st.spinner("Sending emails one at a time..."):
            log_df = send_emails_via_smtp(edited, reports, smtp_settings, period)
        st.session_state["send_log"] = log_df
        st.success("SMTP send attempt complete. Review the log below.")

if "send_log" in st.session_state:
    st.subheader("Send log")
    log_df = st.session_state["send_log"]
    st.dataframe(log_df, use_container_width=True, hide_index=True)
    st.download_button(
        "Download send log CSV",
        data=log_to_csv(log_df),
        file_name="water_cooler_send_log.csv",
        mime="text/csv",
        use_container_width=True,
    )

